import Foundation

public enum ClipboardCapturePolicy {
  private static let sensitiveMarkers = [
    "concealed",
    "transient",
    "password",
    "org.nspasteboard.autogenerated",
    "com.agilebits",
    "onepassword",
  ]

  public static func shouldCapture(typeNames: [String]) -> Bool {
    let normalizedNames = typeNames.map { $0.lowercased() }
    return !normalizedNames.contains { name in
      sensitiveMarkers.contains { name.contains($0) }
    }
  }
}
